language: node_js

node_js:
  - "7.0"
sudo: false

os:
  - linux
  - osx

install:
  - npm install -g vsce
  - npm install -g typescript
  - npm install
  - npm run vscode:prepublish

script:
  - npm run lint
  - npm test --silent

after_success:
  - bash <(curl -s https://codecov.io/bash)
